# Generated by Django 4.0.4 on 2022-06-20 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('Name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Introduction', models.CharField(default='Empty', max_length=65535)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='introduction',
            new_name='Introduction',
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='Mysterious Recording', max_length=255)),
                ('File', models.FileField(upload_to='Recordings')),
                ('UploadUserName', models.CharField(default='Anonymous', max_length=255)),
                ('Description', models.CharField(default='Empty', max_length=65535)),
                ('UploadTime', models.DateTimeField(auto_now=True)),
                ('Composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.composer')),
                ('UploadUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
