<<<<<<< HEAD
# Generated by Django 4.0.5 on 2022-06-28 16:07
=======
# Generated by Django 4.0.4 on 2022-07-01 04:52
>>>>>>> b30f5b2061320073f602570e6df8034c0b6c2bda

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_composer_rename_introduction_user_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='UploadUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recordings', to=settings.AUTH_USER_MODEL),
        ),
    ]
