# Generated by Django 4.0.4 on 2022-07-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_recording_uploaduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='LastEditTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
