# Generated by Django 3.2.13 on 2022-07-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_recording_lastedittime'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='Views',
            field=models.IntegerField(default=0),
        ),
    ]
